// <auto-generated />
using System;
using CADASTRO_USUARIOS.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GERENCIAR_USUARIOS.Migrations
{
    [DbContext(typeof(ContextGerenciarUSUARIOS))]
    partial class ContextGerenciarUSUARIOSModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CADASTRO_USUARIOS.Models.Usuario", b =>
                {
                    b.Property<string>("USUARIO")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "USUARIO");

                    b.Property<DateTime>("ALTERADOEM")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "ALTERADOEM");

                    b.Property<string>("ALTERADOPOR")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "ALTERADOPOR");

                    b.Property<DateTime>("CRIADOEM")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "CRIADOEM");

                    b.Property<string>("CRIADOPOR")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "CRIADOPOR");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasAnnotation("Relational:JsonPropertyName", "EMAIL");

                    b.Property<string>("NIVEL")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "NIVEL");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasAnnotation("Relational:JsonPropertyName", "NOME");

                    b.Property<string>("SENHA")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasAnnotation("Relational:JsonPropertyName", "SENHA");

                    b.HasKey("USUARIO");

                    b.ToTable("USUARIOS");

                    b.HasData(
                        new
                        {
                            USUARIO = "admin",
                            ALTERADOEM = new DateTime(2024, 10, 15, 1, 14, 59, 251, DateTimeKind.Local).AddTicks(8820),
                            ALTERADOPOR = "admin",
                            CRIADOEM = new DateTime(2024, 10, 15, 1, 14, 59, 251, DateTimeKind.Local).AddTicks(8804),
                            CRIADOPOR = "admin",
                            EMAIL = "email@teste.com.br",
                            NIVEL = "A",
                            NOME = "ADMIN",
                            SENHA = "$2a$11$IlnYxBzBJncE22K4KNGHhebxVCDdsbRlKKb8ufoyYGhbEMW25mY4W"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
